backend:
  name: github
  repo: ParalelnaPolisKE/paralelnapoliskosice.sk

display_url: https://www.paralelnapoliskosice.sk

media_folder: static/assets
public_folder: /assets

slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - name: title
        label: Title
        widget: string
      - name: author
        label: Author
        widget: string
      - name: cover
        label: Cover Image
        widget: image
        required: false
      - name: tags
        label: Tags
        widget: list
        required: false
      - name: body
        label: Body
        widget: markdown
  - name: data
    label: Data
    files:
      - name: author
        label: Authors
        file: 'src/data/author.json'
        fields:
          - name: author
            label: Author
            widget: list
            fields:
              - name: id
                label: Name
                widget: string
              - name: twitter
                label: Twitter
                widget: string
